hydra:
  searchpath:
    - pkg://verl.trainer.config

defaults:
  - ppo_trainer
  - _self_

# Data configuration
data:
  train_batch_size: 8
  val_batch_size: 8
  max_prompt_length: 16384
  max_response_length: 16384
  filter_overlong_prompts: False
  truncation: 'error'
  return_raw_chat: True

# Algorithm configuration
algorithm:
  adv_estimator: grpo
  use_kl_in_reward: False

# Actor, Rollout, and Reference model configuration
actor_rollout_ref:
  model:
    use_remove_padding: True
    enable_gradient_checkpointing: True
  actor:
    use_kl_loss: True
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    optim:
      lr: 1e-6
      lr_warmup_steps_ratio: 0.285
      lr_warmup_steps: 100
    ppo_mini_batch_size: 8
    ppo_micro_batch_size_per_gpu: 1
    entropy_coeff: 0
    fsdp_config:
      param_offload: False
      optimizer_offload: False
  rollout:
    n: 5
    name: sglang
    mode: async
    max_model_len: 8192
    log_prob_micro_batch_size_per_gpu: 1
    tensor_model_parallel_size: 4
    gpu_memory_utilization: 0.6
    multi_turn:
      format: hermes
      enable: True
      enable_budget: True
      max_assistant_turns: 100
      max_tool_response_length: 16384
      tokenization_sanity_check_mode: "disable"
  ref:
    log_prob_micro_batch_size_per_gpu: 1
    fsdp_config:
      param_offload: False

# Critic configuration
critic:
  model:
    use_remove_padding: True
    enable_gradient_checkpointing: True
    fsdp_config:
      param_offload: False
      optimizer_offload: False
  optim:
    lr: 1e-5
    lr_warmup_steps_ratio: 0.015
    lr_warmup_steps: 15
  forward_micro_batch_size_per_gpu: 1
  ppo_micro_batch_size_per_gpu: 1

# Trainer configuration
trainer:
  total_epochs: 15
  critic_warmup: 0
  val_before_train: False
  logger: ["console","tensorboard"]
  n_gpus_per_node: 8
  nnodes: 1
  save_freq: 20
  test_freq: 20
  resume_mode: "disable"
